---
common_package:
  - name: git
    state: present
  - name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  - name: iotop
    state: present
  - name: tmux
    state: present
  - name: tree
    state: present

repo_files: epel.repo
