---
- name: Add system user group
  group:
    name: "{{ item.name }}"
    gid: "{{ item.id }}"
  with_items: "{{ system_user_group }}"

- name: Add app user group
  group:
    name: "{{ item.name }}"
    gid: "{{ item.id }}"
  with_items: "{{ app_user_group }}"
  when: inventory_hostname in groups ['development']

- name: Add developer admin group
  group:
    name: "{{ item.name }}"
    gid: "{{ item.id }}"
  with_items: "{{ developer_admin_user_group }}"
  when: inventory_hostname in groups ['development'] or inventory_hostname in groups ['bastion'] or inventory_hostname in groups ['localhost']

- name: Add developer group
  group:
    name: "{{ item.name }}"
    gid: "{{ item.id }}"
  with_items: "{{ developer_user_group }}"
  when: inventory_hostname in groups ['development'] or inventory_hostname in groups ['bastion']

- name: Add system user
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
  with_items: "{{ system_user }}"

- name: Make .ssh of system user
  file:
    dest: /home/{{ item.name }}/.ssh/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0700
  with_items: "{{ system_user }}"

- name: Make authorized_keys of system user
  file:
    dest: /home/{{ item.name }}/.ssh/authorized_keys
    state: touch
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0600
  with_items: "{{ system_user }}"

- name: Make .tmux.conf of system user
  copy:
    src:   roles/user/files/.tmux.conf
    dest:  /home/{{ item.name }}/.tmux.conf
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0644
  with_items: "{{ system_user }}"
  when: inventory_hostname in groups ['development'] or inventory_hostname in groups ['bastion']

- name: Add sudo right to system user
  lineinfile:
    dest: /etc/sudoers.d/{{ item.name }}
    state: present
    create: yes
    line: "{{ item.line }}"
  with_items: "{{ system_admin_sudo_right }}"

- name: Add application user
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
  with_items: "{{ admin_user }}"
  when: inventory_hostname in groups ['development']

- name: Make .ssh of application user
  file:
    dest: /home/{{ item.name }}/.ssh/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0700
  with_items: "{{ admin_user }}"
  when: inventory_hostname in groups ['development']

- name: Make authorized_keys of application user
  file:
    dest: /home/{{ item.name }}/.ssh/authorized_keys
    state: touch
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0600
  with_items: "{{ admin_user }}"
  when: inventory_hostname in groups ['development']

- name: Make .tmux.conf .ssh of application user
  copy:
    src:   roles/user/files/.tmux.conf
    dest:  /home/{{ item.name }}/.tmux.conf
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0644
  with_items: "{{ admin_user }}"
  when: inventory_hostname in groups ['development']

- name: Add sudo right to application user
  lineinfile:
    dest: /etc/sudoers.d/{{ item.name }}
    state: present
    create: yes
    line: "{{ item.line }}"
  with_items: "{{ app_admin_sudo_right }}"
  when: inventory_hostname in groups ['development']

- name: Add developer admin user
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
  with_items: "{{ developer_admin_user }}"
  when: inventory_hostname in groups ['development'] or inventory_hostname in groups ['bastion'] or inventory_hostname in groups ['localhost']

- name: Make .ssh of developer admin user
  file:
    dest: /home/{{ item.name }}/.ssh/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0700
  with_items: "{{ developer_admin_user }}"
  when: inventory_hostname in groups ['development'] or inventory_hostname in groups ['bastion'] or inventory_hostname in groups ['localhost']

- name: Make authorized_keys of developer admin user
  file:
    dest: /home/{{ item.name }}/.ssh/authorized_keys
    state: touch
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0600
  with_items: "{{ developer_admin_user }}"
  when: inventory_hostname in groups ['development'] or inventory_hostname in groups ['bastion'] or inventory_hostname in groups ['localhost']

- name: Make .tmux.conf of developer admin user
  file:
    dest: /home/{{ item.name }}/.tmux.conf
    state: touch
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0644
  with_items: "{{ developer_admin_user }}"
  when: inventory_hostname in groups ['development'] or inventory_hostname in groups ['bastion']

- name: Add sudo right to developer admin user
  lineinfile:
    dest: /etc/sudoers.d/{{ item.name }}
    state: present
    create: yes
    line: "{{ item.line }}"
  with_items: "{{ developer_admin_sudo_right }}"
  when: inventory_hostname in groups ['development'] or inventory_hostname in groups ['bastion'] or inventory_hostname in groups ['localhost']

- name: Add developer user
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
  with_items: "{{ development_user }}"
  when: inventory_hostname in groups ['development'] or inventory_hostname in groups ['bastion']

- name: Make .ssh of developer user
  file:
    dest: /home/{{ item.name }}/.ssh/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0700
  with_items: "{{ development_user }}"
  when: inventory_hostname in groups ['development'] or inventory_hostname in groups ['bastion']

- name: Make authorized_keys of developer user
  file:
    dest: /home/{{ item.name }}/.ssh/authorized_keys
    state: touch
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0600
  with_items: "{{ development_user }}"
  when: inventory_hostname in groups ['development'] or inventory_hostname in groups ['bastion']
