---
development_package:
  - name: gcc
    state: present
  - name: gcc-c++
    state: present
  - name: libffi-devel
    state: present
  - name: libxml2-devel
    state: present
  - name: libxslt
    state: present
  - name: libxslt-devel
    state: present
  - name: libyaml-devel
    state: present
  - name: mysql
    state: present
  - name: mysql-devel
    state: present
  - name: nginx
    state: present
  - name: openssl-devel
    state: present
  - name: readline-devel
    state: present
  - name: sqlite-devel
    state: present
  - name: zlib-devel
    state: present
